version: '3.8'

services:
  chatpdf:
    image: vigneshraghu/chatpdf:latest   # Replace with your Docker Hub image
    container_name: chatpdf
    restart: always
    ports:
      - "8080:8080"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"  # Nginx listens on port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - chatpdf
