version: '3'
services:
  chatpdf:
    image: vigneshraghu/chatpdf
    ports:
      - "8080:8080"  # Make sure your app is running on port 8080
    restart: always

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount the Nginx configuration file
    ports:
      - "80:80"  # Nginx will listen on port 80
    depends_on:
      - chatpdf  # Ensure chatpdf starts before nginx
